services:
  evelyn:
    build: .
    image: evelyn:latest
    container_name: evelyn
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      IN_DOCKER: '1'
      EVELYN_DATA_DIR: /app/data
    ports:
      - '5000:5000'
    volumes:
      - /mnt/data/data/robinbot/dca-webapp/data:/app/data
      - /mnt/data/data/robinbot/dca-webapp/static:/app/static
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
